### ISSUE TITLE
Focal Fossa with Kernel 5.1?

### ISSUE THREAD

**Issue by nicro87** [TomTravis/crouton_Penguin#2]
Hi Tom,

first let me say how amazing it is, that you updated crouton to work with jammy.
But please can you help me and get a focal chroot running.  Is it possible to update the chroot with your script?

What I did so far is:
```
# updated chroot with your fork
sudo ./main.sh -u -n focal -p /media/removable/sdcard/

# tried to run xfce
chronos@localhost /media/removable/sdcard/bin $ sudo ./startxfce4 -n focal
Enter encryption passphrase for focal: 
Entering /media/removable/sdcard/chroots/focal...
/usr/bin/startxfce4: Starting X server

(EE) 
Fatal server error:
(EE) Cannot move old log file "/tmp/Xorg.crouton.1.log" to "/tmp/Xorg.crouton.1.log.old"
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) 
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /media/removable/sdcard/chroots/focal...
```
But it crashes. I did not try a fresh install so far.

Thank you in advance,
Nico

```
Please paste the output of the following command here: sudo edit-chroot -all
chronos@localhost /media/removable/sdcard/bin $ sudo ./edit-chroot -all
name: bullseye
encrypted: no
Entering /media/removable/sdcard/chroots/bullseye...
crouton: version 1-20220111101058~master:a9eafaee
release: bullseye
architecture: amd64
xmethod: xorg
targets: audio,xfce-desktop,xfce
host: version 14588.98.0 (Official Build) stable-channel coral 
kernel: Linux localhost 5.10.106-15290-g6e9d70c8a9b4 #1 SMP PREEMPT Wed May 4 19:29:42 PDT 2022 x86_64 GNU/Linux
freon: yes
Unmounting /media/removable/sdcard/chroots/bullseye...
name: focal
encrypted: yes, locked
Unmounting /media/removable/sdcard/chroots/focal...
```

**Comment by nicro87** [comment]
Sorry xfce is starting now when I remove the file "/tmp/Xorg.crouton.1.log".
But when I try to start vscode or other programms then the chromebook resets as before with the old crouton.

**Comment by TomTravis** [comment]
hello
ok here is the deal
I need to update and push
search for debian chroot or ubuntu chroot
choose your ARCH
mine is arm64

debootstrap --arch arm64 jammy /home/coco/cr/jammy http://ports.ubuntu.com/ubuntu-ports
the works to install change root jammy the debootstrap is updated
See the manpage for (some) documentation.

Running debootstrap from source
-------------------------------

You can run debootstrap from its source tree without installing it. This
can be useful if you want a quick way to make a Debian chroot on another
system, or if you are testing modifications to debootstrap.

First, get the source.

* Either by using git
  git clone https://salsa.debian.org/installer-team/debootstrap.git

* Or by visiting <https://packages.debian.org/source/sid/debootstrap>


download the latest and it works for any chroot 

xiwi crouton is the install for X11 to work X11 need systemd so do many others
the X11 env is not passed to crouton Xdefaults and Xresources are ignored , it will work however the crouton config need to be update global only not local

the X11 server now uses systemd so it hangs, with xiwi config dummy x86 intel driver for the display
after buster the X11 code was updated only xiwi worksnow
I working on systemd for nspawn on system chroot many updates need to be made and tested

this is three chroots on a chome book crostini and one crouton and one nspawn development(systemd)
if you wish to help great let me know
![Screenshot 2022-05-16 8 02 44 PM](https://user-images.githubusercontent.com/46386261/168926408-babd2134-70e8-4e0b-88cb-a6d8bcf206bb.png)


good luck
if you need help let me know?

i use mate and xfce apps and many gnomes apps

**Comment by TomTravis** [comment]
remember X11 now requires systemd it will not work with put help
xiwi is it is,  you have to use it it sort of cool you like it

**Comment by TomTravis** [comment]
ok let me look at Focal Fossa
if debootstrap works you good to go

**Comment by TomTravis** [comment]
[coco@penguin:/usr/share/debootstrap/scripts] $ls -la foc*
lrwxrwxrwx. 1 root root 5 May 17 08:52 focal -> gutsy
[coco@penguin:/usr/share/debootstrap/scripts] $^C
[coco@penguin:/usr/share/debootstrap/scripts] $
the chroot script is present ln to gusty crouton need so edit to make it work debootstrap will work just fine Focal is amd64 only I guess i have amd 64 will try it

**Comment by TomTravis** [comment]
this the update for focal and jammy

https://drive.google.com/file/d/1uZWy7RCqwlg8nnFkteGF3ld-gl1KTpkS/view?usp=sharing
the file is focal_test same deal put it in the chrome Downloads folder
shell 
sudo install -dt /usr/local/bin -m 755 ~/Downloads/focal_test

I has updated target it best to install xiwi, core , audio,extension
sudo focal -p /install/path -r focal -t xiwi,core,audio,extension
has you chromeOS chrome have the crouton extension installed

i use mate 
sudo apt intall mate

your .xinitrc file
pulseaudio --start
exec mate-session 
#or 
# exec xfce4-session

you test xiwi 
xiwi  mate-terminal &
it should connect to X11 and open a window

**Comment by TomTravis** [comment]
(focal)z@localhost:~$ xiwi xfce4-screenshooter&
[3] 18250
(focal)z@localhost:~$ 
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.20.13
X Protocol Version 11, Revision 0
Build Operating System: linux Ubuntu
Current Operating System: Linux localhost 4.4.180-16566-g51163f4278d1 #1 SMP PREEMPT Tue Aug 27 17:13:36 PDT 2019 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=555ab761-03b6-1c4c-b6ca-fd37f7598003/PARTNROFF=1 hashtree=PARTUUID=555ab761-03b6-1c4c-b6ca-fd37f7598003/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=3e8df1ad07c15f9a811aa2a9915a17e8409ccf65 salt=0c7d85cad68fb231a34c12121d933c468594106200a09a1c158d34a9cc182c5e" noinitrd vt.global_cursor_default=0 kern_guid=555ab761-03b6-1c4c-b6ca-fd37f7598003 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 14 December 2021  02:14:13PM
xorg-server 2:1.20.13-1ubuntu1~20.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.5.log", Time: Tue May 17 18:39:42 2022
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20220517171647
release: focal
architecture: amd64
xmethod: xiwi
targets: core,xiwi,audio
host: version 12239.92.0 (Official Build) stable-channel glimmer 
kernel: Linux localhost 4.4.180-16566-g51163f4278d1 #1 SMP PREEMPT Tue Aug 27 17:13:36 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Another instance of croutonclip running, waiting...
Another instance of croutontriggerd running, waiting...
Connected to extension, launched crouton in a window.

(focal)z@localhost:~$ 

It is running installed with focal_test

**Comment by TomTravis** [comment]
![pic](https://user-images.githubusercontent.com/46386261/168947676-092e9c70-6182-438f-9e10-6030cbd41667.png)

**Comment by nicro87** [comment]
Thank you for all the work you've done.
I'll test it as soon as possible and give you a reply.

**Comment by TomTravis** [comment]
this the newest so far, systemd get a new kernel
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux penguin 5.10.101-14962-gede4ccb2bf53 #1 SMP PREEMPT Wed Apr 13 19:47:19 PDT 2022 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure drm.trace=0x106 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 5324800 verity payload=PARTUUID=3c445d83-e78b-4bb9-9c18-de4d251da3bd/PARTNROFF=1 hashtree=PARTUUID=3c445d83-e78b-4bb9-9c18-de4d251da3bd/PARTNROFF=1 hashstart=5324800 alg=sha256 root_hexdigest=ac0a13569e377d9972b1b1f107ea6fb4dd0af7bc3dcc96aecaa7319e1526e55a salt=bd4ba40365c3c6d44feb8ed5eb2a82340d93422656679ad23ba3fa67d6547be8" noinitrd vt.global_cursor_default=0 kern_guid=3c445d83-e78b-4bb9-9c18-de4d251da3bd cpuidle.governor=teo  
Build Date: 16 December 2021  05:08:23PM
xorg-server 2:1.20.11-1+deb11u1 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.13.log", Time: Tue May 17 16:30:21 2022
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
crouton: version 1-20220512214808
release: bullseye
architecture: arm64
xmethod: xiwi
targets: core,xiwi
host: version 14526.89.0 (Official Build) stable-channel jacuzzi 
kernel: Linux penguin 5.10.101-14962-gede4ccb2bf53 #1 SMP PREEMPT Wed Apr 13 19:47:19 PDT 2022 aarch64 GNU/Linux
freon: yes
Another instance of croutonclip running, waiting...
Another instance of croutontriggerd running, waiting...
Connected to extension, launched crouton in a window.
mate-session[547]: WARNING: Could not connect to ConsoleKit: Could not get owner of name 'org.freedesktop.ConsoleKit': no such name
Error executing command as another user: Not authorized

This incident has been reported.
Error executing command as another user: Not authorized

This incident has been reported.
LOL to who>

**Comment by TomTravis** [comment]
hello let me know if you can update the kernel and Xserver in focal. jammy is new, same thing with focal no systemd errors

**Comment by nicro87** [comment]
hello, i updated my focal chroot and everything works except of vscode. but i'd not try xiwi so far. i use an old amd64 chromebook (2018) and mostly i use crouton in guest mode (to save energy)

but you say only xiwi ist working with the new kernel or did i misunderstood?

currently i'm trying to set up a fresh jammy chroot and report if it is working.

**Comment by TomTravis** [comment]
yes xiwi and fresh install needs a power cycle to work it has error on init start then works fine
Jammy is the latest im not clear why Focal is being used .
ok the jammy crouton install in amd64 may fail ,The RSA  keycode may need to, Debootstrap is what I did for amd64 jammy
you may need to install update [vscode](https://code.visualstudio.com/download)

**Comment by TomTravis** [comment]
yes the vscode install and run caused my bullseye to have the machine reset still working in build the source

**Comment by TomTravis** [comment]
for vscode to build node.js has to be built and installed  vscode want run with azure  or some container

**Comment by TomTravis** [comment]
on jammy
https://github.com/nodejs/node/issues/43163
vscode will not build

**Comment by nicro87** [comment]
> yes xiwi and fresh install needs a power cycle to work it has error on init start then works fine Jammy is the latest im not clear why Focal is being used . ok the jammy crouton install in amd64 may fail ,The RSA keycode may need to be updated, Debootstrap is what I did for amd64 jammy you may need to install update [vscode](https://code.visualstudio.com/download)

i use focal because it was the last version that was available last year when i setup my chroot. i configured a lot in this chroot and it would be nice to get it working with kernel 5.1.
in fact everything is working except of vscode. vlc for example is working.

**Comment by nicro87** [comment]
> on jammy [nodejs/node#43163](https://github.com/nodejs/node/issues/43163) vscode will not build

thank you for your support. so if everything else is working i can get around with that. i can use crostini for that.

**Comment by TomTravis** [comment]
well it need work so this mean some edit, the work to get this far was some amount the binaries crash chroots installs maybe due to network connections and file systems so when i get x server working this will check it out, as far as i know crouton is dead now for any future work

**Comment by nicro87** [comment]
yes crouton is dead if not anyone else continues it.
it's a pitty because for older chromebooks like mine it was a full system with very low power consumption.

but maybe is this a real alternative:
https://cb-linux.github.io/breath

it will use chromeos kernel and chromeos drivers but is a full linux distro. my first try with it was not working but it sounds fairly good for me.

**Comment by TomTravis** [comment]
vscode is now working on Jammy or at least yarn is , not i know why Python is so popular

cool try debootstrap, this is what is happening< yarn is FU  you have to play with it, the binary download rebooted my machine, I still working on SUSE for my Xserver, o have two now, this is method for me, remote Xserver, Microsoft like container Azure

I got network Manager working , I cannot get to the networks via chroot yet,

Yes I have nodejs working now, CromeOS will not compile, I need more space , my 16tb drive is coming with I7 Processor, arm64  standalone computers are not on the market only chromebooks, Yes im can now run processes the will kill the chromebook, the chromeOS shell has chroot also,

**Comment by TomTravis** [comment]
vscode crashes and every chroot i have tried Xorg and Xiwi

crostini runs it just fine
![Screenshot 2022-05-23 2 28 18 PM](https://user-images.githubusercontent.com/46386261/169909194-5dd5bfed-7842-4014-a0c7-96dfe4c0a5c6.png)

**Comment by nicro87** [comment]
Thank you for your work I'll try it soon.

**Comment by TomTravis** [comment]
vscode is up let me know if you need help
![Screenshot at 2022-05-31 19-43-01](https://user-images.githubusercontent.com/46386261/171317362-3956b36b-a8e5-4b3c-b5d2-4fc956dec464.png)

**Comment by nicro87** [comment]
Hi, thank you for trying. But no i'm using cb-linux breath now.
With my old chromebook it's much faster than crouton and a real linux but based on the chromeos kernel, so it could use original drivers. before i tried gallium os but there you have no audio.

crouton is a good alternative if you want it alongside with chromeos. but i in fact bought me a used chromebook to have a cheap notebook.

thank you again and have a nice day,
nico
